# 2.2 The Token Object

## 🔠 Understanding the `Token` Object

A `Token` represents a single word, punctuation mark, or symbol. 
Tokens carry all the detailed information that spaCy's pipeline has predicted.

We generally divide token attributes into two categories:
1. **Lexical Attributes**: Inherent properties of the word itself (e.g., is it a number? is it uppercase?).
2. **Linguistic Attributes**: Predictions made by the statistical model based on context (e.g., is it a verb? what is its dependency?).

In [1]:
import spacy
import pandas as pd

nlp = spacy.load("en_core_web_sm")
doc = nlp("Apple earned $1 million in 2023 at spacy.io! ")

## 🔎 Lexical Attributes (Rules-based)

These attributes don't require a statistical model. They are extremely useful for writing fast, rule-based logic (which we will cover in Module 8).

In [2]:
lexical_data = []
for token in doc:
    lexical_data.append({
        "Text": token.text,
        "is_alpha": token.is_alpha,
        "is_punct": token.is_punct,
        "is_space": token.is_space,
        "like_num": token.like_num,   # Understands '1', but also 'one', 'billion'
        "like_url": token.like_url,
        "like_email": token.like_email
    })

pd.DataFrame(lexical_data)

       Text  is_alpha  is_punct  is_space  like_num  like_url  like_email
0     Apple      True     False     False     False     False       False
1    earned      True     False     False     False     False       False
2         $     False     False     False     False     False       False
3         1     False     False     False      True     False       False
4   million      True     False     False      True     False       False
5        in      True     False     False     False     False       False
6      2023     False     False     False      True     False       False
7        at      True     False     False     False     False       False
8  spacy.io     False     False     False     False      True       False
9         !     False      True     False     False     False       False

## 🧠 Linguistic Attributes (Model Predictions)

These rely on the statistical pipeline. They change depending on the context of the sentence.

In [3]:
linguistic_data = []
for token in doc:
    # Skip spaces to keep the table clean
    if token.is_space: 
        continue
        
    linguistic_data.append({
        "Text": token.text,
        "Lemma (Base Form)": token.lemma_,
        "POS (Simple)": token.pos_,
        "Tag (Detailed)": token.tag_,
        "Dependency": token.dep_
    })

pd.DataFrame(linguistic_data)

       Text Lemma (Base Form) POS (Simple) Tag (Detailed) Dependency
0     Apple             Apple        PROPN            NNP      nsubj
1    earned              earn         VERB            VBD       ROOT
2         $                 $          SYM              $   quantmod
3         1                 1          NUM             CD   compound
4   million           million          NUM             CD       dobj
5        in                in          ADP             IN       prep
6      2023              2023          NUM             CD       pobj
7        at                at          ADP             IN       prep
8  spacy.io          spacy.io          NUM             CD       pobj
9         !                 !        PUNCT              .      punct

## 🌳 Token Navigation (The Dependency Tree)

Tokens are connected to each other via a syntactic dependency tree. You can navigate this tree using token properties:
- `token.head`: The parent of the token.
- `token.children`: The tokens that depend on this token.
- `token.ancestors`: All parents up to the root of the sentence.

In [4]:
sentence = nlp("The clever dog quickly chased the red ball.")

# Let's look at the word 'chased' (the root of the sentence)
verb_token = sentence[4]
print(f"Target Token: {verb_token.text}")

# Who is the head of 'chased'?
print(f"Head: {verb_token.head.text}")

# What are the children of 'chased'?
children = [child.text for child in verb_token.children]
print(f"Children: {children}")

print("\nLet's look at the word 'dog':")
dog_token = sentence[2]
print(f"Ancestors of 'dog': {[ancestor.text for ancestor in dog_token.ancestors]}")

Target Token: chased
Head: chased
Children: ['dog', 'quickly', 'ball', '.']

Let's look at the word 'dog':
Ancestors of 'dog': ['chased']